project:
  type: website

website:
  site-url: "https://www.philippkollenda.com"
  title: "Data & Development | Philipp Kollenda"
  description: "Welcome to my website. I am an economist working for the World Bank Group's Long-Term Finance team in the Prosperity Global Practice. On here, I write about data science, economics, sustainable finance and programming."
  navbar:
    left:
      - pages/motivation.qmd
      - pages/research.qmd
      - pages/presentations.qmd
      - pages/teaching.qmd
    right:
      - blog.qmd
      - pages/about.qmd
      - icon: github
        href: https://github.com/pkollenda
      - icon: linkedin
        href: https://www.linkedin.com/in/kollenda/
  page-footer: 
    center: "Copyright 2025, Philipp Kollenda" 
    border: true
  # repo-url: "https://github.com/pkollenda/website/"
  # repo-actions: [issue]
  open-graph: true
  # google-analytics: 
  favicon: "pages/images/favicon.png"

format:
  html:
    # page-layout: full
    theme:
      light: flatly
      dark: darkly
    # css: styles.css
# Other nice themes: lumen, sandstone (with dark banner) or flatly & darkly


